language: go
go:
 - 1.4

env:
  global:
  - PROJECT_ID=paulkinlanme

install:
  - npm install
  - go get -v github.com/spf13/hugo

script: 
  - hugo

before_install:
  - openssl aes-256-cbc -K $encrypted_7d273801291c_key -iv $encrypted_7d273801291c_iv -in id_rsa.enc -out deploy_key -d
  - chmod 600 deploy_key

after_success:
  - eval "$(ssh-agent -s)"
  - ssh-add ./deploy_key
  - rsync -az --delete public/  www-user@130.211.184.192:~/blog/

addons:
  ssh_known_hosts:
  - paul.kinlan.me
  - 130.211.184.192

# Move to new container
sudo: false

# branch whitelist
branches:
  only:
  - master
