language: ruby
rvm:
- 2.2

env:
  global:
  - testing=1

script: 
  - bundle exec jekyll build

before_install:
  - openssl aes-256-cbc -K $encrypted_7d273801291c_key -iv $encrypted_7d273801291c_iv -in id_rsa.enc -out deploy_key -d
  - chmod 600 deploy_key

after_success:
  - eval "$(ssh-agent -s)"
  - ssh-add ./deploy_key
  - ssh -q paul@paul.kinlan.me exit
#  - scp -r public/*  paul@paul.kinlan.me:~/blog/paul.kinlan.me/

addons:
  ssh_known_hosts:
  - paul.kinlan.me

# branch whitelist
branches:
  only:
  - master
