language: ruby
rvm:
- 2.2

env:
  global:
  - testing=1

script: 
  - bundle exec jekyll build

before_install:
  - openssl aes-256-cbc -K $encrypted_7d273801291c_key -iv $encrypted_7d273801291c_iv -in id_rsa.enc -out .travis/deploy_key -d

after_success:
  - ssh-add .travis/deploy_key
  - ssh -q paul@paul.kinlan.me exit

# branch whitelist
branches:
  only:
  - master
