baseurl = "https://paul.kinlan.me/"
languageCode = "en-us"
title = "Tales of a Developer Advocate"
description = "The ramblings and musings of a Developer Advocate for Chrome at Google."

paginate = 10

[permalinks]
  post = "/:title/"

[author]
    name = "Paul Kinlan"
    
[params]
  author = "Paul Kinlan"
  analyticsid = "UA-114468-20"
