baseurl = "https://paul.kinlan.me/"
languageCode = "en-us"
title = "Tales of a Developer Advocate"
description = "The ramblings and musings of a Developer Advocate for Chrome at Google."
Copyright = "Paul Kinlan 2016"

paginate = 20

[permalinks]
  post = "/:title/"

[author]
    name = "Paul Kinlan"
    email = "paul.kinlan@gmail.com"
    
[params]
  author = "Paul Kinlan"
  analyticsid = "UA-114468-20"

[taxonimies]
  tag = "tags"

[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP"]